### ISSUE TITLE
Port number do not come to pm2 satan

### ISSUE THREAD

**Issue by fuson** [yyx990803/pod#17]
PM2 require port number for visualization, but in your code (api.js):

for (var o in appInfo.config) {
        if (
            o !== 'port' &&
            o !== 'node_env' &&
            o !== 'remote' &&
            o !== 'username' &&
            o !== 'password' &&
            o !== 'jsonp'
        ) {
            app[o] = appInfo.config[o]
        }
    }

Maybe you'll remove o !== 'port' ? It will solve the issue.

**Comment by meldsza** [comment]
```js
    var conf = {
        name: appInfo.name,
        script: appInfo.script,
        env: {
            NODE_ENV: appInfo.config.node_env || globalConfig.node_env || 'development',
            PORT: appInfo.config.port //port defined here
        }
    }

    // copy other options and pass it to pm2
    for (var o in appInfo.config) {
        if (
            o !== 'port' && //no need to copy port again
            o !== 'node_env' &&
            o !== 'remote' &&
            o !== 'username' &&
            o !== 'password' &&
            o !== 'jsonp'
        ) {
            conf[o] = appInfo.config[o]
        }
    }
```
