### ISSUE TITLE
Github Webhook - "SyntaxError: Unexpected token u"

### ISSUE THREAD

**Issue by Viv-Rajkumar** [yyx990803/pod#18]
Heya,

Just followed [this](https://github.com/yyx990803/pod/wiki/Using-a-remote-repo) to setup a remote repo with pod.

after running `pod remote app-name organisation/app-name`

I see it successfully pulled the master branch inside the /apps folder(repos folder is empty.). Next up got the web tool started and setup the webhook accordingly.

Wanted to add "bower install" along with npm install when a new fetch is done, so created the .podhook file accordingly and added it to `<pod folder>/apps/<app-name>/`

tweaked ~/.podrc such as:

	{
		"root": "/usr/maidsafe/pod",
		"node_env": "development",
		"default_script": "server.js",
		"apps": {
			"network_visualiser": {
				"remote": "maidsafe/Network-Visualiser",
				"branch": "client-ui",
				"node_env": "production",
				"port": 8080
			}
		},
		"web": {}
	}

Now when I commited to the client-ui branch, I can see the webhook executed from github interface, however the response is:

Headers
Connection: keep-alive
Date: Wed, 18 Jun 2014 13:50:38 GMT
Transfer-Encoding: chunked
X-Powered-By: Express

Body
SyntaxError: Unexpected token u

and ofc it doesn't seem to have done anything.

If i run `pod hooks`, I see:

POD ERR ENOENT, open '/usr/maidsafe/pod/repos/network_visualiser.git/hooks/post-receive'

As i mentioned the repos folder is empty as I'm just using a remote app setup. Also checked the logs from ~/.pm2/logs

Only thing in the err.log is:

connect.multipart() will be removed in connect 3.0

Not sure what I'm doing wrong, or if the webhook just isnt working.

This is from the web monitor/json output:

	[
	  {
		"name": "network_visualiser",
		"port": 8080,
		"broken": false,
		"status": "OFF",
		"uptime": null,
		"memory": null,
		"cpu": null,
		"instanceCount": 0,
		"raw": {
		  "name": "network_visualiser",
		  "repoPath": "/usr/maidsafe/pod/repos/network_visualiser.git",
		  "workPath": "/usr/maidsafe/pod/apps/network_visualiser",
		  "config": {
			"remote": "maidsafe/Network-Visualiser",
			"branch": "client-ui",
			"node_env": "production",
			"port": 8080
		  },
		  "script": "/usr/maidsafe/pod/apps/network_visualiser/server.js",
		  "port": 8080,
		  "instances": null,
		  "broken": false,
		  "uptime": null
		}
	  }
	]

**Comment by cpius** [comment]
I've made the same pull request, but I've also adapted the tests to the changed web hook format from github.

**Comment by maxdeviant** [comment]
@cpius Excellent! I'll close mine out and :+1: yours.

**Comment by xoorath** [comment]
Hey, I'm still getting this issue in 0.7.7
Has the fix not been integrated? If not - is there a workaround for a normal user flow? I'm not even sure where the web app is installed by default...

**Comment by maxdeviant** [comment]
It looks like the npm package hasn't been updated since the PR (#29) got merged.

https://github.com/yyx990803/pod/commit/730edcf72a527732c83f6627515fe07cb2be294b

**Comment by maxdeviant** [comment]
@yyx990803 Could we get a bump to 0.7.8 to push the webhook fix?

**Comment by yyx990803** [comment]
Fix included in 0.8.0.
