### ISSUE TITLE
PM2 dependency is out of date

### ISSUE THREAD

**Issue by bitwit** [yyx990803/pod#26]
We noticed that the pod version of PM2 is at ~0.7.7 but the latest PM2 release is now at ~0.9.4

Two fold question:
1. Would you forsee any issue with us just installing the latest PM2 inside of pod's context in our environments?
2. Is there any plan to officially update this dependency in a new version of pod?

Thanks very much.

**Comment by yyx990803** [comment]
pm2 has been upgraded to latest version in 0.8.0.
