### ISSUE TITLE
pod returns 500 error on first github ping

### ISSUE THREAD

**Issue by kylemcdonald** [yyx990803/pod#55]
This was really confusing for me at first, I followed the instructions exactly for adding a GitHub hook but then I got the red error symbol.

<img width="725" alt="screen shot 2016-04-27 at 23 09 37" src="https://cloud.githubusercontent.com/assets/157106/14874359/3aee9ea8-0ccd-11e6-9cf5-8edc8361d388.png">

The problem is that before GitHub sends any push events, it sends a "ping" event to test if the connection is working. It could be great to have pod respond to that with a 200 OK status instead of throwing the error `TypeError: Cannot read property "length" of undefined`, to avoid confusion.

I added a note about this to the wiki for now https://github.com/yyx990803/pod/wiki/Using-a-remote-repo#3-setup-github-remote-hook

**Comment by taylorzane** [comment]
Good catch. I've definitely run into this when using pod and just ignored it and pushed again. 

This should be relatively easy to implement. Let me see what I can do about this.
