### ISSUE TITLE
pod start, stop and restart hang

### ISSUE THREAD

**Issue by tom2strobl** [yyx990803/pod#65]
Hi there,

when using pod start, stop and restart it hangs and never exits, doesn't print anything to the console either. Starting does seem to work sometimes though when Ctrl+c'ing and hitting `pod list`. I tried to set the env var `DEBUG=api` to get at least some messages what's happening, but that didn't really work. Is there any way to get more verbosity so I can see where things go wrong? For now I assume it has to do with Satan since `pod list` works just fine.

`npm i` installed 0.12.16 of pm2, is that version known to work?

**Comment by mattdeckard** [comment]
This is affecting me as well. Right now I'm in a state where `pod` thinks one of my apps is running but it isn't, and I haven't found any way to get it too since all the start, stop, and restart commands just hang indefinitely.

**Comment by mattdeckard** [comment]
@tom2strobl Don't know if this will help you but the following steps allowed me to work around this:

- `pkill -9 PM2` to shut down pm2 as the `pm2 kill` command also was hanging
- `pkill node` to kill any running node processes
- Install node version 6.9.1 (was previously running 7.2.0)
- `pod list` should show all apps as OFF and will kick back off pm2

Now that everything is running with node 6.9.1 I'm not having any other issues with hanging.

**Comment by tom2strobl** [comment]
@mattdeckard yeah something along that lines also worked for us, although hacky and not really a solution. Good to hear I'm not the only one!

**Comment by Grynn** [comment]
pod also acting wonky for me; hangs with no output on console. 

node: 7.5.0
pm2@0.12.16

Based on comment from @mattdeckard 

Tried:
```
sudo apt-get remove nodejs
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install nodejs=6.9.* yarn
sudo pkill -9 PM2
sudo pkill node
sudo yarn global add pod
pod web start
pod start foo
pod list   # all good!
pod web status # all good!
```

Seems to be stable now.

**Comment by octalmage** [comment]
I was having similar issues and the solution from @Grynn worked, plus removing pm2 and letting pod reinstall it. I had another version of pm2 installed and it was causing additional issues after completing the steps above. Just running npm uninstall -g pm2 wasn't enough, I had to manually delete the binary. After that pod seems to be working as expected.
