### ISSUE TITLE
POD ERR method "findByFullPath" does not exist

### ISSUE THREAD

**Issue by tuytuy** [yyx990803/pod#74]
I get this error when trying to run an app generated with express-generator.
I don't undestand where the error could be ? Is is a NodeJS error or an internal pod error ?
Please help !!

**Comment by tuytuy** [comment]
any idea ? anyone ?

**Comment by meldsza** [comment]
Yeah the latest pm2 has dropped findByFullPath in [this commit](https://github.com/Unitech/pm2/commit/6a2d52d400b7f9a65ae31609206b948d4772c375#diff-4ce9aea92d36e9c98f1eae56904b4a3e)
i hope pod can transition to a newer version of pm2
